// Comprehensive seed data for Barcelona - all modules

export const barcelonaHotspots = {
  "urban-heat": [
    {
      name: "Eixample District Heat Island",
      description: "Dense grid layout with limited green space showing temperatures 5.8°C above average. The famous blocks trap heat between buildings.",
      severity: "critical" as const,
      displayValue: "+5.8°C",
      neighborhood: "Eixample",
      offset: { lat: 0.008, lng: 0.012 },
      metrics: [{ key: "tempDiff", value: 5.8, unit: "°C" }],
    },
    {
      name: "Zona Franca Industrial Zone",
      description: "Large industrial and logistics area with extensive asphalt surfaces and minimal vegetation.",
      severity: "critical" as const,
      displayValue: "+6.4°C",
      neighborhood: "Zona Franca",
      offset: { lat: -0.025, lng: -0.035 },
      metrics: [{ key: "tempDiff", value: 6.4, unit: "°C" }],
    },
    {
      name: "Plaça Catalunya Commercial Hub",
      description: "Major commercial intersection with high foot traffic and extensive paved surfaces.",
      severity: "high" as const,
      displayValue: "+4.2°C",
      neighborhood: "Ciutat Vella",
      offset: { lat: 0.002, lng: 0.004 },
      metrics: [{ key: "tempDiff", value: 4.2, unit: "°C" }],
    },
    {
      name: "Glòries Shopping Complex",
      description: "Large shopping center and surrounding parking areas creating localized heat accumulation.",
      severity: "high" as const,
      displayValue: "+4.5°C",
      neighborhood: "Sant Martí",
      offset: { lat: 0.015, lng: 0.025 },
      metrics: [{ key: "tempDiff", value: 4.5, unit: "°C" }],
    },
    {
      name: "Sants Railway Station Area",
      description: "Transportation hub with extensive infrastructure and limited green coverage.",
      severity: "medium" as const,
      displayValue: "+3.1°C",
      neighborhood: "Sants-Montjuïc",
      offset: { lat: -0.008, lng: -0.015 },
      metrics: [{ key: "tempDiff", value: 3.1, unit: "°C" }],
    },
  ],
  "coastal-plastic": [
    {
      name: "Barceloneta Beach Accumulation",
      description: "Popular urban beach showing high plastic accumulation, especially microplastics from tourism and urban runoff.",
      severity: "critical" as const,
      displayValue: "380 kg/week",
      neighborhood: "Barceloneta",
      offset: { lat: -0.012, lng: 0.018 },
      metrics: [{ key: "plasticVolume", value: 380, unit: "kg/week" }],
    },
    {
      name: "Port Olímpic Marina",
      description: "Marina area with accumulated fishing debris and recreational boat waste.",
      severity: "high" as const,
      displayValue: "245 kg/week",
      neighborhood: "Vila Olímpica",
      offset: { lat: 0.005, lng: 0.035 },
      metrics: [{ key: "plasticVolume", value: 245, unit: "kg/week" }],
    },
    {
      name: "Bogatell Beach Hotspot",
      description: "Beach area where currents deposit floating debris from the Mediterranean.",
      severity: "medium" as const,
      displayValue: "165 kg/week",
      neighborhood: "Sant Martí",
      offset: { lat: 0.018, lng: 0.042 },
      metrics: [{ key: "plasticVolume", value: 165, unit: "kg/week" }],
    },
    {
      name: "Besòs River Mouth",
      description: "River outflow carrying urban plastic waste into the sea. Major source point for Mediterranean pollution.",
      severity: "critical" as const,
      displayValue: "520 kg/week",
      neighborhood: "Sant Adrià",
      offset: { lat: 0.035, lng: 0.055 },
      metrics: [{ key: "plasticVolume", value: 520, unit: "kg/week" }],
    },
  ],
  "ocean-plastic": [
    {
      name: "Mediterranean Gyre Fragment Zone",
      description: "Offshore area where Mediterranean currents concentrate floating plastic debris from coastal cities.",
      severity: "high" as const,
      displayValue: "2,450 items/km²",
      neighborhood: "Offshore Barcelona",
      offset: { lat: 0.08, lng: 0.12 },
      metrics: [{ key: "debrisDensity", value: 2450, unit: "items/km²" }],
    },
    {
      name: "Costa Brava Current Path",
      description: "Tracking zone for debris moving along the Costa Brava current towards Barcelona.",
      severity: "medium" as const,
      displayValue: "1,120 items/km²",
      neighborhood: "Northeast Offshore",
      offset: { lat: 0.15, lng: 0.08 },
      metrics: [{ key: "debrisDensity", value: 1120, unit: "items/km²" }],
    },
    {
      name: "Balearic Drift Zone",
      description: "Area monitoring plastic flow between Barcelona coast and Balearic Islands.",
      severity: "medium" as const,
      displayValue: "890 items/km²",
      neighborhood: "Southeast Offshore",
      offset: { lat: -0.05, lng: 0.18 },
      metrics: [{ key: "debrisDensity", value: 890, unit: "items/km²" }],
    },
  ],
  "port-emissions": [
    {
      name: "Barcelona Port Terminal A",
      description: "Main container terminal with heavy vessel traffic. Cruise ships and cargo vessels idling while docked.",
      severity: "critical" as const,
      displayValue: "42 t CO₂/day",
      neighborhood: "Port de Barcelona",
      offset: { lat: -0.018, lng: 0.008 },
      metrics: [{ key: "emissions", value: 42, unit: "t CO₂/day" }],
    },
    {
      name: "Cruise Terminal World Trade Center",
      description: "Major cruise terminal with large ships running auxiliary engines during passenger operations.",
      severity: "high" as const,
      displayValue: "28 t CO₂/day",
      neighborhood: "Port Vell",
      offset: { lat: -0.008, lng: 0.012 },
      metrics: [{ key: "emissions", value: 28, unit: "t CO₂/day" }],
    },
    {
      name: "Moll Adossat Ferry Terminal",
      description: "Ferry terminal with daily services to Balearic Islands generating significant emissions.",
      severity: "high" as const,
      displayValue: "18 t CO₂/day",
      neighborhood: "Moll Adossat",
      offset: { lat: -0.022, lng: 0.002 },
      metrics: [{ key: "emissions", value: 18, unit: "t CO₂/day" }],
    },
    {
      name: "ZAL Logistics Anchorage",
      description: "Waiting area for cargo vessels, ships often idle for hours awaiting berth assignment.",
      severity: "medium" as const,
      displayValue: "12 t CO₂/day",
      neighborhood: "Zona Franca Port",
      offset: { lat: -0.032, lng: -0.015 },
      metrics: [{ key: "emissions", value: 12, unit: "t CO₂/day" }],
    },
  ],
  "biodiversity": [
    {
      name: "Ciutadella Park Connectivity Gap",
      description: "Major urban park needing better ecological corridors to connect with other green spaces.",
      severity: "medium" as const,
      displayValue: "6.2/10",
      neighborhood: "Ciutat Vella",
      offset: { lat: 0.003, lng: 0.018 },
      metrics: [{ key: "biodiversityScore", value: 6.2, unit: "/10" }],
    },
    {
      name: "Collserola-City Interface",
      description: "Critical zone where Collserola Natural Park meets urban development. Potential wildlife corridor.",
      severity: "high" as const,
      displayValue: "7.8/10",
      neighborhood: "Sarrià-Sant Gervasi",
      offset: { lat: 0.045, lng: -0.025 },
      metrics: [{ key: "biodiversityScore", value: 7.8, unit: "/10" }],
    },
    {
      name: "Superblock Biodiversity Opportunity",
      description: "Network of traffic-calmed superblocks presenting opportunity for green corridor development.",
      severity: "low" as const,
      displayValue: "4.5/10",
      neighborhood: "Sant Martí",
      offset: { lat: 0.012, lng: 0.022 },
      metrics: [{ key: "biodiversityScore", value: 4.5, unit: "/10" }],
    },
    {
      name: "Montjuïc Hill Ecosystem",
      description: "Large green area with potential for expanded native species habitat and pollinator corridors.",
      severity: "low" as const,
      displayValue: "8.1/10",
      neighborhood: "Sants-Montjuïc",
      offset: { lat: -0.015, lng: -0.008 },
      metrics: [{ key: "biodiversityScore", value: 8.1, unit: "/10" }],
    },
  ],
  "restoration": [
    {
      name: "Former Poblenou Industrial Site",
      description: "Abandoned factory area in 22@ district suitable for urban garden and green space conversion.",
      severity: "high" as const,
      displayValue: "8.5/10 potential",
      neighborhood: "Poblenou",
      offset: { lat: 0.008, lng: 0.028 },
      metrics: [{ key: "restorationPotential", value: 8.5, unit: "/10" }],
    },
    {
      name: "Can Batlló Community Project",
      description: "Former textile factory being transformed into community gardens and cultural space.",
      severity: "medium" as const,
      displayValue: "7.2/10 potential",
      neighborhood: "La Bordeta",
      offset: { lat: -0.012, lng: -0.022 },
      metrics: [{ key: "restorationPotential", value: 7.2, unit: "/10" }],
    },
    {
      name: "La Sagrera Rail Corridor",
      description: "Railway corridor offering opportunity for linear park and ecological connectivity.",
      severity: "high" as const,
      displayValue: "9.0/10 potential",
      neighborhood: "Sant Andreu",
      offset: { lat: 0.025, lng: 0.015 },
      metrics: [{ key: "restorationPotential", value: 9.0, unit: "/10" }],
    },
    {
      name: "Besòs Riverbank Restoration",
      description: "Degraded riverbank area with high potential for wetland restoration and flood mitigation.",
      severity: "critical" as const,
      displayValue: "9.2/10 potential",
      neighborhood: "Sant Adrià de Besòs",
      offset: { lat: 0.038, lng: 0.045 },
      metrics: [{ key: "restorationPotential", value: 9.2, unit: "/10" }],
    },
  ],
};

export const barcelonaQuickWins = {
  "urban-heat": [
    {
      title: "Eixample Green Corridors",
      description: "Plant shade trees along Passeig de Gràcia and adjacent streets to reduce heat in Barcelona's densest district.",
      impact: "high" as const,
      effort: "medium" as const,
      estimatedDays: 90,
      co2ReductionTons: 45,
      tags: ["trees", "cooling", "eixample"],
      steps: [
        "Survey existing tree coverage on main boulevards",
        "Identify suitable species for Mediterranean climate",
        "Coordinate with city planning for planting zones",
        "Install irrigation systems for new trees",
        "Plant 200 new shade trees along corridors",
      ],
    },
    {
      title: "Cool Roofs Initiative - El Raval",
      description: "Install reflective roof coatings on buildings in El Raval to reduce heat absorption.",
      impact: "medium" as const,
      effort: "low" as const,
      estimatedDays: 45,
      co2ReductionTons: 25,
      tags: ["roofs", "cooling", "raval"],
      steps: [
        "Identify 50 buildings with dark roofs",
        "Partner with local contractors for installations",
        "Provide subsidies for building owners",
        "Monitor temperature reductions",
      ],
    },
  ],
  "coastal-plastic": [
    {
      title: "Barceloneta Beach Cleanup Program",
      description: "Establish regular community beach cleanups with local schools and organizations.",
      impact: "high" as const,
      effort: "low" as const,
      estimatedDays: 30,
      co2ReductionTons: 5,
      tags: ["cleanup", "community", "beach"],
      steps: [
        "Partner with 10 local schools and NGOs",
        "Schedule monthly cleanup events",
        "Provide equipment and waste sorting training",
        "Track plastic collected and types",
      ],
    },
    {
      title: "Besòs River Trash Traps",
      description: "Install floating debris barriers at key points along the Besòs River to intercept plastic before it reaches the sea.",
      impact: "high" as const,
      effort: "medium" as const,
      estimatedDays: 60,
      co2ReductionTons: 8,
      tags: ["river", "infrastructure", "prevention"],
      steps: [
        "Survey optimal trap locations",
        "Design barriers suitable for river flow",
        "Install 5 debris capture systems",
        "Establish weekly collection schedule",
      ],
    },
  ],
  "port-emissions": [
    {
      title: "Shore Power Connection - Cruise Terminal",
      description: "Enable cruise ships to connect to grid electricity while docked, eliminating auxiliary engine emissions.",
      impact: "high" as const,
      effort: "high" as const,
      estimatedDays: 180,
      co2ReductionTons: 1200,
      tags: ["port", "electricity", "cruise"],
      steps: [
        "Assess electrical grid capacity",
        "Design shore power infrastructure",
        "Install connection points at 3 berths",
        "Coordinate with cruise lines for adoption",
      ],
    },
    {
      title: "Ferry Fleet Hybrid Conversion",
      description: "Pilot hybrid electric propulsion for Balearic ferry services to reduce emissions in port.",
      impact: "medium" as const,
      effort: "high" as const,
      estimatedDays: 365,
      co2ReductionTons: 450,
      tags: ["ferry", "hybrid", "pilot"],
      steps: [
        "Select 2 ferries for pilot program",
        "Partner with Baleària for conversion",
        "Install hybrid propulsion systems",
        "Monitor fuel savings and emissions",
      ],
    },
  ],
  "biodiversity": [
    {
      title: "Pollinator Highway - Diagonal Avenue",
      description: "Create a continuous pollinator corridor along Avinguda Diagonal with native flowering plants.",
      impact: "medium" as const,
      effort: "medium" as const,
      estimatedDays: 120,
      co2ReductionTons: 15,
      tags: ["pollinators", "diagonal", "flowers"],
      steps: [
        "Map existing green spaces along Diagonal",
        "Select Mediterranean pollinator plants",
        "Install native plant beds at 20 locations",
        "Add bee hotels and insect habitats",
      ],
    },
    {
      title: "Rooftop Habitats Program",
      description: "Convert 50 building rooftops into green roofs supporting urban biodiversity.",
      impact: "high" as const,
      effort: "medium" as const,
      estimatedDays: 180,
      co2ReductionTons: 40,
      tags: ["rooftops", "green", "habitat"],
      steps: [
        "Identify suitable buildings with strong roofs",
        "Design standardized green roof kit",
        "Partner with property owners",
        "Install bird boxes and insect hotels",
      ],
    },
  ],
  "restoration": [
    {
      title: "Poblenou Urban Garden Network",
      description: "Transform vacant lots in Poblenou into community gardens and pocket parks.",
      impact: "high" as const,
      effort: "low" as const,
      estimatedDays: 90,
      co2ReductionTons: 20,
      tags: ["gardens", "community", "poblenou"],
      steps: [
        "Identify 10 vacant lots for conversion",
        "Test soil quality and remediate if needed",
        "Design participatory garden layouts",
        "Engage neighborhood associations",
        "Plant native and edible species",
      ],
    },
    {
      title: "Besòs Wetland Restoration Phase 1",
      description: "Begin restoring natural wetland habitat along the Besòs riverbank for flood control and biodiversity.",
      impact: "high" as const,
      effort: "high" as const,
      estimatedDays: 365,
      co2ReductionTons: 150,
      tags: ["wetland", "river", "restoration"],
      steps: [
        "Complete environmental impact assessment",
        "Remove invasive species from 2 hectares",
        "Reshape riverbank for natural flooding",
        "Plant native wetland species",
        "Install wildlife monitoring equipment",
      ],
    },
  ],
};
