// Seed data for quick wins
// moduleSlug is used to link to the module after seeding
export const quickWinsSeedData = [
  // Urban Heat (12 quick wins)
  {
    moduleSlug: "urban-heat",
    title: "Install cool roofs on municipal buildings",
    description:
      "Apply reflective coatings to reduce building temperatures by up to 5°C and decrease cooling costs",
    impact: "high" as const,
    effort: "medium" as const,
    estimatedDays: 30,
    tags: ["infrastructure", "cooling", "buildings"],
    category: "Infrastructure",
    sortOrder: 1,
  },
  {
    moduleSlug: "urban-heat",
    title: "Plant 500 street trees in heat hotspots",
    description:
      "Strategic tree planting in identified heat islands to provide natural cooling and shade",
    impact: "high" as const,
    effort: "medium" as const,
    estimatedDays: 90,
    tags: ["trees", "greening", "shade"],
    category: "Greening",
    sortOrder: 2,
  },
  {
    moduleSlug: "urban-heat",
    title: "Create pop-up shade structures",
    description:
      "Deploy temporary shade solutions in public spaces during heat waves",
    impact: "medium" as const,
    effort: "low" as const,
    estimatedDays: 7,
    tags: ["shade", "temporary", "public-space"],
    category: "Quick Deploy",
    sortOrder: 3,
  },
  {
    moduleSlug: "urban-heat",
    title: "Establish cooling centers network",
    description:
      "Designate public buildings as cooling centers during extreme heat events",
    impact: "high" as const,
    effort: "low" as const,
    estimatedDays: 14,
    tags: ["health", "emergency", "community"],
    category: "Community",
    sortOrder: 4,
  },
  {
    moduleSlug: "urban-heat",
    title: "Install misting systems in plazas",
    description:
      "Add water misting in high-traffic public areas for evaporative cooling",
    impact: "medium" as const,
    effort: "low" as const,
    estimatedDays: 21,
    tags: ["cooling", "water", "public-space"],
    category: "Infrastructure",
    sortOrder: 5,
  },
  {
    moduleSlug: "urban-heat",
    title: "Convert parking lots to green spaces",
    description:
      "Transform underused parking areas into vegetated cool zones",
    impact: "high" as const,
    effort: "high" as const,
    estimatedDays: 180,
    tags: ["greening", "land-use", "transformation"],
    category: "Land Use",
    sortOrder: 6,
  },
  {
    moduleSlug: "urban-heat",
    title: "Paint streets with cool pavement coating",
    description:
      "Apply reflective coatings to streets to reduce surface temperatures",
    impact: "medium" as const,
    effort: "medium" as const,
    estimatedDays: 45,
    tags: ["infrastructure", "streets", "coating"],
    category: "Infrastructure",
    sortOrder: 7,
  },
  {
    moduleSlug: "urban-heat",
    title: "Launch heat vulnerability mapping",
    description:
      "Create detailed maps identifying vulnerable populations in heat hotspots",
    impact: "medium" as const,
    effort: "low" as const,
    estimatedDays: 30,
    tags: ["data", "mapping", "equity"],
    category: "Planning",
    sortOrder: 8,
  },
  {
    moduleSlug: "urban-heat",
    title: "Install green facades on public buildings",
    description:
      "Add vertical gardens to building exteriors for cooling and biodiversity",
    impact: "medium" as const,
    effort: "medium" as const,
    estimatedDays: 60,
    tags: ["greening", "buildings", "biodiversity"],
    category: "Greening",
    sortOrder: 9,
  },
  {
    moduleSlug: "urban-heat",
    title: "Create shaded pedestrian corridors",
    description:
      "Design continuous shaded walking routes connecting key destinations",
    impact: "high" as const,
    effort: "high" as const,
    estimatedDays: 120,
    tags: ["mobility", "shade", "connectivity"],
    category: "Infrastructure",
    sortOrder: 10,
  },
  {
    moduleSlug: "urban-heat",
    title: "Implement heat alert notification system",
    description:
      "Deploy SMS and app-based warnings during extreme heat events",
    impact: "medium" as const,
    effort: "low" as const,
    estimatedDays: 14,
    tags: ["technology", "alerts", "health"],
    category: "Technology",
    sortOrder: 11,
  },
  {
    moduleSlug: "urban-heat",
    title: "Subsidize residential cool roofs",
    description:
      "Offer rebates for homeowners to install reflective roofing materials",
    impact: "high" as const,
    effort: "medium" as const,
    estimatedDays: 60,
    tags: ["policy", "residential", "incentives"],
    category: "Policy",
    sortOrder: 12,
  },

  // Coastal Plastic (10 quick wins)
  {
    moduleSlug: "coastal-plastic",
    title: "Deploy trash interceptor at river mouth",
    description:
      "Install floating barriers to capture plastic before it reaches the ocean",
    impact: "high" as const,
    effort: "medium" as const,
    estimatedDays: 45,
    tags: ["infrastructure", "prevention", "rivers"],
    category: "Infrastructure",
    sortOrder: 1,
  },
  {
    moduleSlug: "coastal-plastic",
    title: "Organize weekly beach cleanups",
    description:
      "Coordinate volunteer-driven cleanup events at predicted hotspots",
    impact: "medium" as const,
    effort: "low" as const,
    estimatedDays: 7,
    tags: ["community", "cleanup", "volunteers"],
    category: "Community",
    sortOrder: 2,
  },
  {
    moduleSlug: "coastal-plastic",
    title: "Install smart waste bins on beaches",
    description:
      "Deploy solar-powered compacting bins with fill-level sensors",
    impact: "medium" as const,
    effort: "medium" as const,
    estimatedDays: 30,
    tags: ["technology", "waste", "smart-city"],
    category: "Technology",
    sortOrder: 3,
  },
  {
    moduleSlug: "coastal-plastic",
    title: "Ban single-use plastics in coastal zone",
    description:
      "Implement local legislation prohibiting disposable plastics near beaches",
    impact: "high" as const,
    effort: "high" as const,
    estimatedDays: 180,
    tags: ["policy", "regulation", "prevention"],
    category: "Policy",
    sortOrder: 4,
  },
  {
    moduleSlug: "coastal-plastic",
    title: "Launch citizen science monitoring app",
    description:
      "Deploy mobile app for residents to report and track plastic pollution",
    impact: "medium" as const,
    effort: "medium" as const,
    estimatedDays: 60,
    tags: ["technology", "community", "data"],
    category: "Technology",
    sortOrder: 5,
  },
  {
    moduleSlug: "coastal-plastic",
    title: "Partner with fishing industry for cleanup",
    description:
      "Engage local fishers in collecting marine debris during operations",
    impact: "medium" as const,
    effort: "low" as const,
    estimatedDays: 30,
    tags: ["partnership", "fishing", "collection"],
    category: "Partnership",
    sortOrder: 6,
  },

  // Ocean Plastic Classifier (6 quick wins)
  {
    moduleSlug: "ocean-plastic",
    title: "Train local volunteers on classification",
    description:
      "Run workshops teaching community members to use the classification tool",
    impact: "medium" as const,
    effort: "low" as const,
    estimatedDays: 14,
    tags: ["training", "community", "capacity"],
    category: "Capacity Building",
    sortOrder: 1,
  },
  {
    moduleSlug: "ocean-plastic",
    title: "Deploy classification stations on beaches",
    description:
      "Set up permanent photo submission kiosks at key beach locations",
    impact: "medium" as const,
    effort: "medium" as const,
    estimatedDays: 45,
    tags: ["infrastructure", "technology", "data"],
    category: "Infrastructure",
    sortOrder: 2,
  },
  {
    moduleSlug: "ocean-plastic",
    title: "Integrate with school science programs",
    description:
      "Partner with schools to use classification as educational tool",
    impact: "medium" as const,
    effort: "low" as const,
    estimatedDays: 30,
    tags: ["education", "schools", "engagement"],
    category: "Education",
    sortOrder: 3,
  },
  {
    moduleSlug: "ocean-plastic",
    title: "Create brand accountability dashboard",
    description:
      "Publish data on most frequently found branded items",
    impact: "high" as const,
    effort: "medium" as const,
    estimatedDays: 45,
    tags: ["data", "accountability", "transparency"],
    category: "Data & Reporting",
    sortOrder: 4,
  },

  // Port Emissions (9 quick wins)
  {
    moduleSlug: "port-emissions",
    title: "Implement shore power for docked vessels",
    description:
      "Enable ships to plug into grid power instead of running diesel generators",
    impact: "high" as const,
    effort: "high" as const,
    estimatedDays: 365,
    tags: ["infrastructure", "electrification", "ships"],
    category: "Infrastructure",
    sortOrder: 1,
  },
  {
    moduleSlug: "port-emissions",
    title: "Establish vessel speed reduction zone",
    description:
      "Create slow-steaming zones near port to reduce emissions",
    impact: "medium" as const,
    effort: "low" as const,
    estimatedDays: 30,
    tags: ["policy", "regulation", "speed"],
    category: "Policy",
    sortOrder: 2,
  },
  {
    moduleSlug: "port-emissions",
    title: "Deploy air quality monitors at port",
    description:
      "Install real-time air quality sensors to track pollution levels",
    impact: "medium" as const,
    effort: "low" as const,
    estimatedDays: 21,
    tags: ["monitoring", "air-quality", "data"],
    category: "Monitoring",
    sortOrder: 3,
  },
  {
    moduleSlug: "port-emissions",
    title: "Transition port vehicles to electric",
    description:
      "Replace diesel equipment with electric alternatives",
    impact: "medium" as const,
    effort: "medium" as const,
    estimatedDays: 180,
    tags: ["electrification", "vehicles", "operations"],
    category: "Operations",
    sortOrder: 4,
  },
  {
    moduleSlug: "port-emissions",
    title: "Create green shipping corridor partnership",
    description:
      "Partner with other ports to establish zero-emission shipping routes",
    impact: "high" as const,
    effort: "high" as const,
    estimatedDays: 365,
    tags: ["partnership", "shipping", "corridor"],
    category: "Partnership",
    sortOrder: 5,
  },
  {
    moduleSlug: "port-emissions",
    title: "Publish real-time emissions dashboard",
    description:
      "Make port emissions data publicly accessible for transparency",
    impact: "medium" as const,
    effort: "medium" as const,
    estimatedDays: 60,
    tags: ["data", "transparency", "public"],
    category: "Data & Reporting",
    sortOrder: 6,
  },
  {
    moduleSlug: "port-emissions",
    title: "Incentivize cleaner vessels",
    description:
      "Offer reduced port fees for ships meeting emission standards",
    impact: "medium" as const,
    effort: "medium" as const,
    estimatedDays: 90,
    tags: ["policy", "incentives", "standards"],
    category: "Policy",
    sortOrder: 7,
  },
  {
    moduleSlug: "port-emissions",
    title: "Install wind barriers to reduce dispersion",
    description:
      "Deploy barriers to direct emissions away from residential areas",
    impact: "low" as const,
    effort: "medium" as const,
    estimatedDays: 120,
    tags: ["infrastructure", "mitigation", "community"],
    category: "Infrastructure",
    sortOrder: 8,
  },
  {
    moduleSlug: "port-emissions",
    title: "Create buffer zone with vegetation",
    description:
      "Plant trees and shrubs between port and residential areas",
    impact: "medium" as const,
    effort: "medium" as const,
    estimatedDays: 90,
    tags: ["greening", "buffer", "air-quality"],
    category: "Greening",
    sortOrder: 9,
  },

  // Biodiversity (12 quick wins)
  {
    moduleSlug: "biodiversity",
    title: "Create pollinator gardens in parks",
    description:
      "Plant native flowering species to support bees and butterflies",
    impact: "medium" as const,
    effort: "low" as const,
    estimatedDays: 30,
    tags: ["pollinators", "gardens", "native-plants"],
    category: "Habitat Creation",
    sortOrder: 1,
  },
  {
    moduleSlug: "biodiversity",
    title: "Install bird nesting boxes",
    description:
      "Deploy species-specific nesting structures in urban green spaces",
    impact: "low" as const,
    effort: "low" as const,
    estimatedDays: 14,
    tags: ["birds", "nesting", "wildlife"],
    category: "Wildlife Support",
    sortOrder: 2,
  },
  {
    moduleSlug: "biodiversity",
    title: "Establish wildlife corridors",
    description:
      "Connect fragmented habitats with continuous green pathways",
    impact: "high" as const,
    effort: "high" as const,
    estimatedDays: 365,
    tags: ["corridors", "connectivity", "habitat"],
    category: "Habitat Connectivity",
    sortOrder: 3,
  },
  {
    moduleSlug: "biodiversity",
    title: "Convert lawns to native meadows",
    description:
      "Replace monoculture grass with diverse native plant communities",
    impact: "medium" as const,
    effort: "medium" as const,
    estimatedDays: 60,
    tags: ["meadows", "native-plants", "conversion"],
    category: "Habitat Creation",
    sortOrder: 4,
  },
  {
    moduleSlug: "biodiversity",
    title: "Create urban wetland habitat",
    description:
      "Design stormwater features that double as wildlife habitat",
    impact: "high" as const,
    effort: "high" as const,
    estimatedDays: 180,
    tags: ["wetlands", "stormwater", "habitat"],
    category: "Habitat Creation",
    sortOrder: 5,
  },
  {
    moduleSlug: "biodiversity",
    title: "Launch BioBlitz citizen science events",
    description:
      "Organize community species counting events to document biodiversity",
    impact: "medium" as const,
    effort: "low" as const,
    estimatedDays: 14,
    tags: ["citizen-science", "monitoring", "community"],
    category: "Monitoring",
    sortOrder: 6,
  },
  {
    moduleSlug: "biodiversity",
    title: "Install bat houses",
    description:
      "Provide roosting habitat for urban bat populations",
    impact: "low" as const,
    effort: "low" as const,
    estimatedDays: 7,
    tags: ["bats", "roosting", "wildlife"],
    category: "Wildlife Support",
    sortOrder: 7,
  },
  {
    moduleSlug: "biodiversity",
    title: "Create insect hotels",
    description:
      "Build structures providing habitat for beneficial insects",
    impact: "low" as const,
    effort: "low" as const,
    estimatedDays: 7,
    tags: ["insects", "habitat", "pollinators"],
    category: "Wildlife Support",
    sortOrder: 8,
  },
  {
    moduleSlug: "biodiversity",
    title: "Reduce light pollution in parks",
    description:
      "Install wildlife-friendly lighting to protect nocturnal species",
    impact: "medium" as const,
    effort: "medium" as const,
    estimatedDays: 60,
    tags: ["lighting", "nocturnal", "parks"],
    category: "Habitat Protection",
    sortOrder: 9,
  },
  {
    moduleSlug: "biodiversity",
    title: "Remove invasive species",
    description:
      "Systematically remove non-native plants threatening local ecosystems",
    impact: "medium" as const,
    effort: "medium" as const,
    estimatedDays: 90,
    tags: ["invasives", "removal", "restoration"],
    category: "Habitat Protection",
    sortOrder: 10,
  },
  {
    moduleSlug: "biodiversity",
    title: "Create green roofs on public buildings",
    description:
      "Install biodiverse green roofs to extend urban habitat",
    impact: "medium" as const,
    effort: "high" as const,
    estimatedDays: 120,
    tags: ["green-roofs", "buildings", "habitat"],
    category: "Habitat Creation",
    sortOrder: 11,
  },
  {
    moduleSlug: "biodiversity",
    title: "Plant native trees along streets",
    description:
      "Replace non-native street trees with local species supporting wildlife",
    impact: "medium" as const,
    effort: "medium" as const,
    estimatedDays: 90,
    tags: ["trees", "native-plants", "streets"],
    category: "Greening",
    sortOrder: 12,
  },

  // Restoration (8 quick wins)
  {
    moduleSlug: "restoration",
    title: "Restore degraded urban forest",
    description:
      "Rehabilitate neglected woodland areas with native species",
    impact: "high" as const,
    effort: "high" as const,
    estimatedDays: 365,
    tags: ["forest", "restoration", "native-plants"],
    category: "Forest Restoration",
    sortOrder: 1,
  },
  {
    moduleSlug: "restoration",
    title: "Daylight buried streams",
    description:
      "Uncover channelized waterways to restore natural stream habitat",
    impact: "high" as const,
    effort: "high" as const,
    estimatedDays: 730,
    tags: ["streams", "daylighting", "habitat"],
    category: "Water Restoration",
    sortOrder: 2,
  },
  {
    moduleSlug: "restoration",
    title: "Create community food forest",
    description:
      "Establish edible forest gardens on underutilized public land",
    impact: "medium" as const,
    effort: "medium" as const,
    estimatedDays: 180,
    tags: ["food-forest", "community", "edible"],
    category: "Community Restoration",
    sortOrder: 3,
  },
  {
    moduleSlug: "restoration",
    title: "Restore brownfield to park",
    description:
      "Convert contaminated industrial site into ecological park",
    impact: "high" as const,
    effort: "high" as const,
    estimatedDays: 730,
    tags: ["brownfield", "remediation", "park"],
    category: "Land Restoration",
    sortOrder: 4,
  },
  {
    moduleSlug: "restoration",
    title: "Plant riparian buffer zones",
    description:
      "Establish vegetated strips along waterways for habitat and water quality",
    impact: "medium" as const,
    effort: "medium" as const,
    estimatedDays: 90,
    tags: ["riparian", "water-quality", "habitat"],
    category: "Water Restoration",
    sortOrder: 5,
  },
  {
    moduleSlug: "restoration",
    title: "Remove concrete from riverbanks",
    description:
      "Replace hard engineering with natural bank stabilization",
    impact: "medium" as const,
    effort: "high" as const,
    estimatedDays: 365,
    tags: ["rivers", "naturalization", "engineering"],
    category: "Water Restoration",
    sortOrder: 6,
  },
  {
    moduleSlug: "restoration",
    title: "Establish seed bank of native species",
    description:
      "Collect and store local plant genetics for restoration projects",
    impact: "medium" as const,
    effort: "medium" as const,
    estimatedDays: 180,
    tags: ["seeds", "genetics", "native-plants"],
    category: "Resource Development",
    sortOrder: 7,
  },
  {
    moduleSlug: "restoration",
    title: "Launch tree sponsorship program",
    description:
      "Enable residents to fund and track individual tree plantings",
    impact: "low" as const,
    effort: "low" as const,
    estimatedDays: 30,
    tags: ["community", "funding", "trees"],
    category: "Community Engagement",
    sortOrder: 8,
  },
];
