/* eslint-disable */
/**
 * Generated by Convex.
 * This file is a stub - run `npx convex dev` to generate actual types.
 */

import { AnyApi } from "convex/server";

export const api: AnyApi = {} as AnyApi;
export const internal: AnyApi = {} as AnyApi;
