/* eslint-disable */
/**
 * Generated by Convex.
 * This file is a stub - run `npx convex dev` to generate actual types.
 */

import { GenericDataModel, GenericDocument, GenericTableInfo } from "convex/server";

export type DataModel = GenericDataModel;

export type Doc<TableName extends string> = GenericDocument;
export type Id<TableName extends string> = string;
