/* eslint-disable */
/**
 * Generated by Convex.
 * This file is a stub - run `npx convex dev` to generate actual types.
 */

import {
  ActionBuilder,
  HttpActionBuilder,
  MutationBuilder,
  QueryBuilder,
  GenericActionCtx,
  GenericMutationCtx,
  GenericQueryCtx,
  GenericDatabaseReader,
  GenericDatabaseWriter,
} from "convex/server";
import { DataModel } from "./dataModel";

export const query: QueryBuilder<DataModel, "public"> = (() => {
  throw new Error("Convex not configured");
}) as unknown as QueryBuilder<DataModel, "public">;

export const internalQuery: QueryBuilder<DataModel, "internal"> = (() => {
  throw new Error("Convex not configured");
}) as unknown as QueryBuilder<DataModel, "internal">;

export const mutation: MutationBuilder<DataModel, "public"> = (() => {
  throw new Error("Convex not configured");
}) as unknown as MutationBuilder<DataModel, "public">;

export const internalMutation: MutationBuilder<DataModel, "internal"> = (() => {
  throw new Error("Convex not configured");
}) as unknown as MutationBuilder<DataModel, "internal">;

export const action: ActionBuilder<DataModel, "public"> = (() => {
  throw new Error("Convex not configured");
}) as unknown as ActionBuilder<DataModel, "public">;

export const internalAction: ActionBuilder<DataModel, "internal"> = (() => {
  throw new Error("Convex not configured");
}) as unknown as ActionBuilder<DataModel, "internal">;

export const httpAction: HttpActionBuilder = (() => {
  throw new Error("Convex not configured");
}) as unknown as HttpActionBuilder;

export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type ActionCtx = GenericActionCtx<DataModel>;
export type DatabaseReader = GenericDatabaseReader<DataModel>;
export type DatabaseWriter = GenericDatabaseWriter<DataModel>;
